export const LOAD_BLOG = 'LOAD_BLOG';
export const LOAD_BLOG_SUCCESS = 'LOAD_BLOG_SUCCESS';
export const LOAD_BLOG_FAIL = 'LOAD_BLOG_FAIL';
export const LOAD_BLOG_BY_ID = 'LOAD_BLOG_BY_ID';
export const LOAD_BLOG_BY_ID_SUCCESS = 'LOAD_BLOG_BY_ID_SUCCESS';
export const LOAD_BLOG_BY_ID_FAIL = 'LOAD_BLOG_BY_ID_FAIL';

export const CREATE_BLOG = 'CREATE_BLOG';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAIL = 'CREATE_BLOG_FAIL';

export const UPDATE_BLOG = 'UPDATE_BLOG';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL';

export const DELETE_BLOG = 'DELETE_BLOG';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL';


