export const LOAD_BLOGTYPE = 'LOAD_BLOGTYPE';
export const LOAD_BLOGTYPE_SUCCESS = 'LOAD_BLOGTYPE_SUCCESS';
export const LOAD_BLOGTYPE_FAIL = 'LOAD_BLOGTYPE_FAIL';
export const LOAD_BLOGTYPE_BY_ID = 'LOAD_BLOGTYPE_BY_ID';
export const LOAD_BLOGTYPE_BY_ID_SUCCESS = 'LOAD_BLOGTYPE_BY_ID_SUCCESS';
export const LOAD_BLOGTYPE_BY_ID_FAIL = 'LOAD_BLOGTYPE_BY_ID_FAIL';

export const CREATE_BLOGTYPE = 'CREATE_BLOGTYPE';
export const CREATE_BLOGTYPE_SUCCESS = 'CREATE_BLOGTYPE_SUCCESS';
export const CREATE_BLOGTYPE_FAIL = 'CREATE_BLOGTYPE_FAIL';

export const UPDATE_BLOGTYPE = 'UPDATE_BLOGTYPE';
export const UPDATE_BLOGTYPE_SUCCESS = 'UPDATE_BLOGTYPE_SUCCESS';
export const UPDATE_BLOGTYPE_FAIL = 'UPDATE_BLOGTYPE_FAIL';

export const DELETE_BLOGTYPE = 'DELETE_BLOGTYPE';
export const DELETE_BLOGTYPE_SUCCESS = 'DELETE_BLOGTYPE_SUCCESS';
export const DELETE_BLOGTYPE_FAIL = 'DELETE_BLOGTYPE_FAIL';


